name: mixy_app
description: "A simple Flutter app that generates and saves random word pairs."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  english_words: ^4.0.0
  provider: ^6.1.5
  shared_preferences: ^2.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/mix.png"

flutter:
  uses-material-design: true
